# -*- coding: utf-8 -*-
"""Vineeth Krishnan_Predictive Maintenance_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Aw0glsp6HO-pdvrM4UQjoFFmjDKwQeG

#*Problem Statement & Business Context*

Vehicle breakdowns and engine failures lead to significant financial losses for both individual owners and fleet operators. Unexpected engine failures can cause expensive repairs, operational downtime, and safety risks. Predictive maintenance in the automotive industry can help minimize these issues by leveraging sensor data to forecast potential failures before they occur.

Goal is to build a predictive maintenance model that can analyze historical and real-time engine sensor data to identify potential failures. The model should accurately classify whether an engine requires maintenance or is operating normally.

This solution will help:

Reduce unplanned breakdowns and costly repairs.
Improve vehicle performance and engine lifespan.
Optimize maintenance schedules to minimize downtime
Provide data-driven insights to manufacturers and fleet operators for better decision-making.

# *Libraries Installation*
"""

!pip install datasets huggingface_hub mlflow scikit-learn pandas matplotlib seaborn joblib streamlit

from xgboost import XGBClassifier

"""

Huggingface Authentication

"""

# HUGGING FACE AUTHENTICATION

from huggingface_hub import login
login(token="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")

# Define your Hugging Face username and repository names
HF_USERNAME = "vnsonly05"
DATASET_REPO_ID = f"vnsonly05/engine-condition-data"
MODEL_REPO_ID = f"vnsonly05/engine-condition-rf-model"

api = HfApi()

"""# *Data Registration*"""

# Create a master folder and "data" subfolder
master_folder = "enginepredict  "
data_folder = os.path.join(master_folder, "data")
os.makedirs(data_folder, exist_ok=True)
print(f"Created folders: {data_folder}")

"""Upload the csv file to data folder"""

# Load data into Hugging Face Dataset format and register (Push to Hub)
target_csv_path = os.path.join(data_folder, "engine_data.csv")
if os.path.exists(target_csv_path):
    print(f"Found dataset directly at: {target_csv_path}")
else:
    print(f"WARNING: Please upload 'engine_data.csv' directly into the '{data_folder}' folder in the file explorer.")
raw_dataset = Dataset.from_csv(target_csv_path)
print("Pushing raw dataset to Hugging Face Hub...")
# Note: This will create a new dataset repo on your HF account
raw_dataset.push_to_hub(DATASET_REPO_ID, private=False)
print(f"Dataset successfully registered at: https://huggingface.co/datasets/{DATASET_REPO_ID}")

"""# *EDA*

Data Collection and Background:

The dataset contains operational metrics of an engine (RPM, various pressures, and temperatures).
The goal is to predict the 'Engine Condition' (0 = Faulty, 1 = Healthy) based on these parameters.
"""

df = pd.read_csv(target_csv_path)

# Data Overview
print("\nData Overview:")
display(df.info())
display(df.describe())

# Separate column types for plotting
numerical_cols = ['Engine rpm', 'Lub oil pressure', 'Fuel pressure', 'Coolant pressure', 'lub oil temp', 'Coolant temp']
target_col = 'Engine Condition'

"""UNIVARIATE ANALYSIS: Categorical Variables"""

# UNIVARIATE ANALYSIS
# 1. Categorical Variable (Target): Countplot & Pie Chart
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
# Countplot
sns.countplot(data=df, x=target_col, palette='Set2', ax=axes[0])
# Pie Chart
engine_counts = df[target_col].value_counts()
axes[1].pie(engine_counts, labels=['Healthy (1)', 'Faulty (0)'],
            autopct='%1.1f%%', colors=['#66b3ff','#ff9999'], startangle=90)
axes[1].set_title(f'Pie Chart: {target_col}')

plt.tight_layout()
plt.show()

"""UNIVARIATE ANALYSIS: Numerical Variables"""

# 2. Numerical Variables: Histograms & Boxplots
print("\nPlotting Histograms and Boxplots for numerical variables...")
for col in numerical_cols:
    fig, axes = plt.subplots(1, 2, figsize=(14, 4))

    # Histogram with KDE (Distribution)
    sns.histplot(df[col], kde=True, color='skyblue', ax=axes[0])
    axes[0].set_title(f'Histogram & KDE: {col}')

    # Boxplot (Outlier detection)
    sns.boxplot(x=df[col], color='lightgreen', ax=axes[1])
    axes[1].set_title(f'Boxplot: {col}')

    plt.tight_layout()
    plt.show()

"""BIVARIATE ANALYSIS"""

# Detailed Bivariate: How does each numerical feature relate to the Target?
# We use boxplots grouped by the target to see the difference in distributions
plt.figure(figsize=(16, 10))
for i, col in enumerate(numerical_cols, 1):
    plt.subplot(2, 3, i)
    sns.boxplot(data=df, x=target_col, y=col, palette='Set2')
    plt.title(f'{col} vs {target_col}')
plt.tight_layout()
plt.show()

# Bivariate Scatterplot Example: RPM vs Temperatures colored by Engine Condition
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sns.scatterplot(data=df, x='Engine rpm', y='Coolant temp', hue=target_col, alpha=0.6, palette='Set1', ax=axes[0])
axes[0].set_title('Engine RPM vs Coolant Temp')

sns.scatterplot(data=df, x='Engine rpm', y='lub oil temp', hue=target_col, alpha=0.6, palette='Set1', ax=axes[1])
axes[1].set_title('Engine RPM vs Lub Oil Temp')
plt.tight_layout()
plt.show()

"""MULTIVARIATE ANALYSIS"""

# 1. Pairplot: Visualizing interactions between multiple variables at once
print("Generating Pairplot (This might take a few seconds)...")
sns.pairplot(df, hue=target_col, palette='Set2', corner=True, diag_kind='kde')
plt.suptitle('Pairplot of All Numerical Variables grouped by Target', y=1.02)
plt.show()

# 2. Correlation Heatmap
print("Generating Correlation Heatmap...")
plt.figure(figsize=(10, 8))
corr = df.corr()

# Create a mask to hide the upper triangle for better readability (optional but looks clean)
mask = np.triu(np.ones_like(corr, dtype=bool))

sns.heatmap(corr, mask=mask, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5, vmin=-1, vmax=1)
plt.title('Multivariate Analysis: Feature Correlation Heatmap')
plt.show()

"""EDA INSIGHTS & OBSERVATIONS:
1. Target Distribution: The target variable (Engine Condition) is relatively balanced, as seen in the Pie Chart.
2. Feature Distributions: Most numerical features (like Lub oil pressure and Coolant pressure) follow a somewhat normal/Gaussian distribution, though varying ranges indicate that scaling (like StandardScaler) is highly recommended.
4. Bivariate & Multivariate Interactions: The pairplot and correlation matrix reveal if any pairs of features are highly collinear (e.g., redundant features).

# *Data Preparation*
"""

# Load dataset directly from Hugging Face data space
print("Loading dataset from Hugging Face Hub...")
hf_data = load_dataset(DATASET_REPO_ID, split="train")
df_prep = hf_data.to_pandas()

# Perform Data Cleaning
print("Performing Data Cleaning...")
df_prep = df_prep.drop_duplicates()
print(f"Data shape after removing duplicates: {df_prep.shape}")

# Split into X and y
X = df_prep.drop(columns=['Engine Condition'])
y = df_prep['Engine Condition']

# Train-Test Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Save them locally
train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)

train_path = os.path.join(data_folder, "train.csv")
test_path = os.path.join(data_folder, "test.csv")
train_df.to_csv(train_path, index=False)
test_df.to_csv(test_path, index=False)
print("Train and Test datasets saved locally.")

# Upload train and test datasets back to Hugging Face
print("Uploading Train/Test splits back to Hugging Face Hub...")
dataset_dict = DatasetDict({
    "train": Dataset.from_pandas(train_df, preserve_index=False),
    "test": Dataset.from_pandas(test_df, preserve_index=False)
})
dataset_dict.push_to_hub(DATASET_REPO_ID)
print("Train/Test splits successfully pushed to Hugging Face Hub!")

"""# *MODEL BUILDING WITH EXPERIMENTATION TRACKING*"""

#Loading Train/Test data directly from the newly pushed Hugging Face dataset
print("Loading train/test splits from HF Hub for Modeling...")
hf_splits = load_dataset(DATASET_REPO_ID)
X_train_hf = hf_splits['train'].to_pandas().drop(columns=['Engine Condition'])
y_train_hf = hf_splits['train'].to_pandas()['Engine Condition']
X_test_hf = hf_splits['test'].to_pandas().drop(columns=['Engine Condition'])
y_test_hf = hf_splits['test'].to_pandas()['Engine Condition']

# Set up local MLflow tracking in Colab
mlflow.set_tracking_uri("file://" + os.path.abspath("mlruns"))
mlflow.set_experiment("Engine_Prediction")

# Define Models and Parameters to Tune using a dictionary
models_to_train = {
    "RandomForest": {
        "model": RandomForestClassifier(random_state=42),
        "params": {
            'n_estimators': [50, 100],
            'max_depth': [10, None],
            'min_samples_split': [2, 5]
        }
    },
    "XGBoost": {
        "model": XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss'),
        "params": {
            'n_estimators': [50, 100],
            'max_depth': [3, 6],
            'learning_rate': [0.01, 0.1]
        }
    }
}

# Dictionaries to store the best trained models and their scores for comparison
best_models = {}
model_scores = {}

print("Starting MLflow Runs & Hyperparameter Tuning for multiple models...\n")

# Iterate over both models, tune them, and log them to MLflow
for model_name, config in models_to_train.items():
    print(f"--- Tuning {model_name} ---")

    # Start a distinct MLflow run for each model
    with mlflow.start_run(run_name=f"{model_name}_Hyperparameter_Tuning"):

        # Tune the model using GridSearchCV
        grid_search = GridSearchCV(estimator=config["model"], param_grid=config["params"], cv=3, scoring='accuracy', n_jobs=-1)
        grid_search.fit(X_train_hf, y_train_hf)

        # Extract the best model and parameters
        best_model = grid_search.best_estimator_
        best_params = grid_search.best_params_

        print(f"Best Parameters for {model_name}: {best_params}")

        # Log Tuned Parameters to MLflow
        mlflow.log_params(best_params)

# Evaluate the model performance on the test set
y_pred = best_model.predict(X_test_hf)
accuracy = accuracy_score(y_test_hf, y_pred)

print(f"{model_name} Accuracy on Test Set: {accuracy:.4f}")
print(f"Classification Report for {model_name}:\n", classification_report(y_test_hf, y_pred))

# Log metrics & the model itself to MLflow
mlflow.log_metric("accuracy", accuracy)
mlflow.sklearn.log_model(best_model, f"{model_name}_model")

# Store results for later comparison
best_models[model_name] = best_model
model_scores[model_name] = accuracy
print("-" * 50)

# DETERMINE THE OVERALL BEST MODEL
# Find the model name that yielded the highest accuracy score
overall_best_model_name = max(model_scores, key=model_scores.get)
overall_best_model = best_models[overall_best_model_name]
overall_best_score = model_scores[overall_best_model_name]

print(f"\n=======================================================")
print(f"OVERALL BEST MODEL: {overall_best_model_name} with Accuracy: {overall_best_score:.4f}")
print(f"=======================================================\n")

# REGISTER THE BEST MODEL TO HUGGING FACE
print("Registering the overall Best Model to Hugging Face Hub...")

# Save the winning model locally using joblib
model_filename = f"best_{overall_best_model_name.lower()}_engine_model.joblib"
joblib.dump(overall_best_model, model_filename)

# Create a repo on Hugging Face (if it doesn't exist)
api.create_repo(repo_id=MODEL_REPO_ID, repo_type="model", exist_ok=True)

# Upload the winning model file to Hugging Face
api.upload_file(
    path_or_fileobj=model_filename,
    path_in_repo=model_filename,
    repo_id=MODEL_REPO_ID,
    repo_type="model",
    commit_message=f"Uploaded tuned {overall_best_model_name} model (Test Accuracy: {overall_best_score:.4f})"
)

print(f"Best Model successfully registered at: https://huggingface.co/{MODEL_REPO_ID}")

"""# *MODEL DEPLOYMENT*"""

import os
from huggingface_hub import HfApi

HF_USERNAME = "vnsonly05"
MODEL_REPO_ID = f"{HF_USERNAME}/engine-condition-rf-model"
MODEL_FILENAME = "best_xgboost_engine_model.joblib"
SPACE_NAME = "Engine-Predictive-Maintenance"
SPACE_ID = f"{HF_USERNAME}/{SPACE_NAME}"

# Create a deployment folder
deploy_dir = "deployment"
os.makedirs(deploy_dir, exist_ok=True)

# ---------------------------------------------------------
# A. Create app.py (Streamlit Application)
# ---------------------------------------------------------
app_code = f"""import streamlit as st
import pandas as pd
import joblib
from huggingface_hub import hf_hub_download

# Configuration
MODEL_REPO_ID = "{MODEL_REPO_ID}"
MODEL_FILENAME = "{MODEL_FILENAME}"

@st.cache_resource
def load_model():
    # Load the saved model directly from the Hugging Face model hub
    model_path = hf_hub_download(repo_id=MODEL_REPO_ID, filename=MODEL_FILENAME)
    return joblib.load(model_path)

try:
    model = load_model()
    st.success("Model loaded successfully from Hugging Face Hub!")
except Exception as e:
    st.error(f"Error loading model: {{e}}")

st.title("Engine Failure Prediction")
st.write("Enter the real-time sensor data below to predict if the engine is Healthy or Faulty.")

# Get inputs from the user
col1, col2 = st.columns(2)
with col1:
    engine_rpm = st.number_input("Engine RPM", min_value=0, value=700)
    lub_oil_pressure = st.number_input("Lubrication Oil Pressure", value=2.5)
    fuel_pressure = st.number_input("Fuel Pressure", value=11.5)
with col2:
    coolant_pressure = st.number_input("Coolant Pressure", value=3.0)
    lub_oil_temp = st.number_input("Lubrication Oil Temperature", value=84.0)
    coolant_temp = st.number_input("Coolant Temperature", value=81.0)

if st.button("Predict Engine Condition"):
    # Save inputs into a pandas dataframe
    input_data = pd.DataFrame({{
        'Engine rpm': [engine_rpm],
        'Lub oil pressure': [lub_oil_pressure],
        'Fuel pressure': [fuel_pressure],
        'Coolant pressure': [coolant_pressure],
        'lub oil temp': [lub_oil_temp],
        'Coolant temp': [coolant_temp]
    }})

    st.write("### Captured Input DataFrame:")
    st.dataframe(input_data)

    # Predict
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.success("✅ Prediction: Engine is Healthy (1)")
    else:
        st.error("🚨 Prediction: Engine is Faulty (0) - Maintenance Required!")
"""
with open(os.path.join(deploy_dir, "app.py"), "w") as f:
    f.write(app_code)

# ---------------------------------------------------------
# B. Create requirements.txt
# ---------------------------------------------------------
requirements_code = """streamlit
pandas
scikit-learn
xgboost
huggingface_hub
joblib
"""
with open(os.path.join(deploy_dir, "requirements.txt"), "w") as f:
    f.write(requirements_code)

# ---------------------------------------------------------
# C. Create Dockerfile
# ---------------------------------------------------------
dockerfile_code = """FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
"""
with open(os.path.join(deploy_dir, "Dockerfile"), "w") as f:
    f.write(dockerfile_code)

print(f"✅ Deployment files (app.py, requirements.txt, Dockerfile) generated in '{deploy_dir}' folder.")

# ---------------------------------------------------------
# D. Push to Hugging Face Spaces
# ---------------------------------------------------------
api = HfApi()
print(f"Creating Hugging Face Space: {SPACE_ID}...")
try:
    # FIX: Changed space_sdk from "streamlit" to "docker"
    api.create_repo(repo_id=SPACE_ID, repo_type="space", space_sdk="docker", exist_ok=True)

    files_to_push = ["app.py", "requirements.txt", "Dockerfile"]
    for file in files_to_push:
        file_path = os.path.join(deploy_dir, file)
        api.upload_file(
            path_or_fileobj=file_path,
            path_in_repo=file,
            repo_id=SPACE_ID,
            repo_type="space"
        )
    print(f"✅ Deployment files successfully pushed!")
    print(f"🔗 View your live app here: https://huggingface.co/spaces/{SPACE_ID}")
except Exception as e:
    print(f"Error pushing to HF Spaces: {e}. Please ensure your HF Token has 'Write' permissions.")

"""#*Actionable Business Insights*

1. Do Not Fully Automate Maintenance Yet: Because the model misses roughly 2 out of 3 actual engine failures, it is currently too risky to replace standard preventive maintenance schedules entirely. Deploying it as the sole trigger for repairs would lead to unexpected, costly breakdowns on the track. Treat the current model as an "assistant" rather than an autonomous decision-maker

2. Continuous Model Retraining Strategy (MLOps): Re-run the MLflow pipeline quarterly with new data to ensure the model adapts to aging engines over time.

3. Implement Cost-Sensitive Learning in MLOps: In the MLflow pipeline, the models should be retrained using Class Weights (e.g., class_weight='balanced') or data resampling techniques like SMOTE. The algorithm needs to be mathematically penalized heavily for missing a faulty engine so it stops blindly guessing "Healthy".

4. Implement Rule-Based Dashboards Immediately: While the ML model undergoes improvements, the business should use the findings from the Bivariate EDA to set up hard-coded safety alerts. For example, if the boxplots showed that a healthy engine rarely exceeds a specific Coolant Temperature, set up an automatic telemetry dashboard alert to trigger if a kart crosses that exact threshold, completely independent of the Machine Learning model.
"""